#!/bin/bash
# Quick Git Reference Card for Marketing Automation Repository

echo "=========================================="
echo "📦 MARKETING AUTOMATION REPOSITORY"
echo "=========================================="
echo ""
echo "🔗 Repository URL:"
echo "   https://github.com/PrameshLuitel/marketing-automation"
echo "   (PRIVATE REPO)"
echo ""
echo "=========================================="
echo "🚀 QUICK UPDATE COMMANDS"
echo "=========================================="
echo ""
echo "1️⃣  QUICKEST - Using push script:"
echo "   ./push.sh \"Added new feature\""
echo ""
echo "2️⃣  Manual commands:"
echo "   git add ."
echo "   git commit -m \"Your message\""
echo "   git push origin main"
echo ""
echo "3️⃣  Pull latest (from another machine):"
echo "   git pull origin main"
echo ""
echo "=========================================="
echo "📊 CHECK STATUS"
echo "=========================================="
echo ""
echo "   git status              # See changed files"
echo "   git log --oneline -5    # Last 5 commits"
echo "   git remote -v           # Check remote URL"
echo ""
echo "=========================================="
echo "⚠️  IMPORTANT FILES NOT TRACKED"
echo "=========================================="
echo ""
echo "These are in .gitignore and won't be pushed:"
echo "   - .env files (API keys)"
echo "   - node_modules/ (dependencies)"
echo "   - venv/ (Python virtual env)"
echo "   - data/ (databases, outputs)"
echo "   - *.mp4, *.png, *.jpg (media files)"
echo "   - *.log (log files)"
echo ""
echo "=========================================="
echo "🔧 SETUP ON NEW MACHINE"
echo "========================================""
echo ""
echo "   git clone https://github.com/PrameshLuitel/marketing-automation.git"
echo "   cd marketing-automation"
echo "   "
echo "   # Backend"
echo "   cd backend"
echo "   python -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo "   cp .env.example .env  # Add your API keys"
echo "   "
echo "   # Frontend"
echo "   cd ../frontend"
echo "   npm install"
echo "   "
echo "   # Video Renderer"
echo "   cd ../video-renderer"
echo "   npm install"
echo ""
echo "=========================================="
